runtime: nodejs22

env_variables:
  NODE_ENV: "production"

# Serve static files from .output/public using express server
entrypoint: npm start

automatic_scaling:
  min_instances: 0
  max_instances: 1
